name: ğŸ“±ğŸŒ Mobile App Production Build

on:
  workflow_dispatch:
    inputs:
      backend_branch:
        description: 'Branch for the backend'
        required: false
        default: 'production'
        type: string
      mobile_branch:
        description: 'Branch for the mobile app'
        required: false
        default: 'master'
        type: string

jobs:
  build:
    uses: ./.github/workflows/app-build.yml
    with:
      build_type: production
      mobile_branch: ${{ github.event.inputs.mobile_branch }}
      backend_branch: ${{ github.event.inputs.backend_branch }}