name: Lint, Test and Security Check

on:
  workflow_call:
    inputs:
      runner_image_name:
        description: "Name of the runner image"
        required: true
        type: string
      deploy_localstack:
        description: "Whether to run Terraform plan and apply steps"
        type: boolean
        default: false

jobs:
  lint-test-security:
    name: Lint, Test and Security Check
    runs-on: ${{ vars.RUNNER_OS }}
    environment: ci
    env:
      RUNNER_IMAGE_NAME: ${{ inputs.runner_image_name }}
      LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
      TF_VAR_google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ” Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ“‘ Validate OpenAPI specs
        run: make run-command-lint-api

      - name: ğŸ“¦ Install Node Modules
        run: make run-command-install-node-packages

      - name: ğŸ§ª Unit Test Code
        run: make run-command-test

      - name: ğŸ§ Lint Code
        run: make run-command-lint-code

      - name: ğŸ Package Code
        run: make run-command-package-all

      - name: ğŸ¬ Start Localstack
        run: make localstack-start

      - name: ğŸ›¡ï¸ Terraform Security
        run: make run-command-tf-security

      - name: ğŸ“‘ Terraform Validation
        run: make run-command-tf-validate

      - name: ğŸ› ï¸ Terraform Initialization Localstack
        run: make run-command-tf-init

      - name: ğŸ—“ï¸ Terraform Plan Localstack
        if: ${{ inputs.deploy_localstack }}
        run: make run-command-tf-plan-apply

      - name: ğŸš€ Terraform Apply Localstack
        if: ${{ inputs.deploy_localstack }}
        run: make run-command-tf-apply

      - name: ğŸ“Š Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: unittest-coverage-report
          path: coverage/coverage-summary.json
